### PR TITLE
Add functionality for TRV

### PR DESCRIPTION
**Pull request by livehybrid**
New Class (EnergenieTemperature) to get current/target temperature for Energenie eTRV.
Allows setting of target temperature (set_temp)

### CODE REVIEW

**Comment by livehybrid** [comment]
@ng110 Anything I can do to help get this merged? Cheers

**Comment by ng110** [comment]
Hi.  Thanks for the PR and sorry for the slow response.  I have very little time to spend on this (also this is the first time I have had a contribution on a project, so figuring out how things work!), but will try to review and merge before too long.  By the way, I see you have also forked HomeAssistant.  If you are trying to use this library with HA, you might like to compare notes with my fork at https://github.com/ng110/home-assistant (the switch platform works a bit!).

**Comment by livehybrid** [comment]
Hi. No worries,
Ive pushed my changes for Climate integration for the Energenie eTRVs (See screenshot - Ignore the fact its so cold...).
The changes to HomeAssistant are here:
https://github.com/livehybrid/home-assistant/commit/b24611fd1cffc151abc988ee2c6d4363b513ac76

Let me know if you have any comments!
screenshot 2019-01-05 at 18 47 33
screenshot 2019-01-05 at 18 47 29

**Comment by livehybrid** [comment]
@ng110 Bump?

**Comment by ng110** [comment]
Hi.  sorry about this.  Not forgotten; I just get very little time for such things.  I should get a bit of time in a couple of weeks or so if it'll wait that long.

**Review by ng110 — APPROVED** [review]
Hi.  Sorry for the delay.  Accepting the PR now, but will make a couple of little mods before the next release.  I will also add a 'develop' branch for any future PRs.

**Pull request merged**
